// apps/astriarch-frontend-sveltekit/src/lib/components/astriarch/top-overview-item/TopOverviewItem.svelte
<script lang="ts">
	import type { IconImageType } from '../types.js';
	import Text from '../text/Text.svelte';
	import IconImage from '../icon-image/IconImage.svelte';

	interface Props {
		amount: number;
		amountPerTurn?: number;
		type: IconImageType;
		onClick?: () => void;
		children?: any;
		class?: string;
	}

	let {
		amount = 0,
		amountPerTurn,
		type,
		onClick,
		children,
		class: className,
		...restProps
	}: Props = $props();

	const amountFormatted = $derived((amount ?? 0).toFixed(1));
	const amountPerTurnFormatted = $derived(amountPerTurn ? amountPerTurn.toFixed(1) : null);
	const amountPerTurnSign = $derived(amountPerTurn ? (amountPerTurn > 0 ? '+' : '') : '');
	const amountContent = $derived(
		amountPerTurn
			? `${amountFormatted}  ${amountPerTurnSign}${amountPerTurnFormatted}`
			: amountFormatted.toString()
	);

	const textStyle = $derived(`
    color: #FFF;
    font-size: 18px;
    font-weight: 600;
    line-height: 32px;
    letter-spacing: 0.09px;
    margin-left: 4px;
    display: inline-block;
    vertical-align: bottom;
    ${['food', 'ore', 'iridium'].includes(type) ? 'min-width: 110px;' : 'min-width: 65px;'}
  `);

	function handleClick() {
		onClick?.();
	}
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<div
	class="relative z-[100] flex {className || ''}"
	onclick={handleClick}
	onkeydown={(e) => {
		if (onClick && (e.key === 'Enter' || e.key === ' ')) {
			e.preventDefault();
			handleClick();
		}
	}}
	role={onClick ? 'button' : undefined}
	tabindex={onClick ? 0 : undefined}
	{...restProps}
>
	<IconImage {type} size={32} />
	<Text style={textStyle}>
		{amountContent}
	</Text>
	{#if children}
		{@render children()}
	{/if}
</div>

// packages/astriarch-ui/src/components/TopOverviewItem/index.tsx
import { Box } from "@chakra-ui/react";
import React from "react";
import Text from "../Text";
import IconImage from "../IconImage";

export interface TopOverviewItemProps {
  children?: React.ReactNode;
  amount: number;
  amountPerTurn?: number;
  type: 'population' | 'food' | 'energy' | 'research' | 'ore' | 'iridium';
  onClick?: () => void;
}

const TopOverviewItem: React.FC<TopOverviewItemProps> = (props) => {
  const { children, amount, amountPerTurn, type,  ...rest } = props;
  const amountFormatted = Math.floor(amount);
  const amountPerTurnFormatted = amountPerTurn ? amountPerTurn.toFixed(1) : null;
  const amountPerTurnSign = amountPerTurn ? (amountPerTurn > 0 ? "+" : "") : "";
  const amountContent = amountPerTurn ? `${amountFormatted}  ${amountPerTurnSign}${amountPerTurnFormatted}` : amountFormatted;
  const additionalTextCss = {
    color: "#FFF",
    fontSize: "18px",
    fontWeight: 600,
    lineHeight: "32px",
    letterSpacing: "0.09px",
  };

  return (
    <Box {...rest} position={"relative"} display={'flex'} css={{ zIndex: 100}}>
      <IconImage type={type} size={32} />
      <Text css={{ marginLeft: 4, display: "inline-block", ...additionalTextCss }} verticalAlign={"bottom"}>
        {amountContent}
      </Text>
      
      {children}
    </Box>
  );
};

export default TopOverviewItem;
