// packages/astriarch-ui/src/components/Dialog/index.tsx
import { ReactNode } from "react";
import { Button, CloseButton, Dialog, Portal } from "@chakra-ui/react";

export interface DialogProps {
  onChange?: (index: number) => void;
  placement?: React.ComponentProps<typeof Dialog.Root>["placement"];
  title?: string;
  children?: ReactNode;
  onCancel?: () => void;
  onSave?: () => void;
  cancelButtonText?: string;
  saveButtonText?: string;
}

/**
 * Dialog component using Chakra UI v3 Dialog component
 */
const DialogComponent: React.FC<DialogProps> = ({
  placement = "top",
  title = "Dialog Title",
  cancelButtonText = "Cancel",
  saveButtonText = "Save",
  onChange,
  onCancel,
  onSave,
  ...rest
}) => {
  return (
    <Dialog.Root placement={placement} motionPreset="slide-in-bottom">
      <Portal>
        <Dialog.Backdrop />
        <Dialog.Positioner>
          <Dialog.Content>
            <Dialog.Header>
              <Dialog.Title>{title}</Dialog.Title>
            </Dialog.Header>
            <Dialog.Body>{rest.children}</Dialog.Body>
            <Dialog.Footer>
              <Button variant="outline" onClick={onCancel}>
                {cancelButtonText}
              </Button>
              <Button onClick={onSave}>{saveButtonText}</Button>
            </Dialog.Footer>
            <CloseButton position="absolute" top="3" right="3" size="sm" />
          </Dialog.Content>
        </Dialog.Positioner>
      </Portal>
    </Dialog.Root>
  );
};

export default DialogComponent;

// Export additional Dialog sub-components for more flexibility
export { Dialog };

// apps/astriarch-frontend-sveltekit/src/lib/components/astriarch/dialog/Dialog.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button";
  import * as Dialog from "$lib/components/ui/dialog";
  
  interface Props {
    title?: string;
    cancelButtonText?: string;
    saveButtonText?: string;
    open?: boolean;
    onCancel?: () => void;
    onSave?: () => void;
    children?: any;
  }
  
  let { 
    title = "Dialog Title",
    cancelButtonText = "Cancel", 
    saveButtonText = "Save",
    open = false,
    onCancel,
    onSave,
    children,
    ...restProps 
  }: Props = $props();
</script>

<Dialog.Root bind:open>
  <Dialog.Content class="sm:max-w-[425px]">
    <Dialog.Header>
      <Dialog.Title>{title}</Dialog.Title>
    </Dialog.Header>
    <Dialog.Description class="sr-only">
      Dialog content
    </Dialog.Description>
    
    <div class="py-4">
      {@render children?.()}
    </div>
    
    <Dialog.Footer class="flex gap-2">
      <Button variant="outline" onclick={onCancel}>
        {cancelButtonText}
      </Button>
      <Button onclick={onSave}>
        {saveButtonText}
      </Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>
