// packages/astriarch-ui/src/components/TabController/index.tsx
import { Box, TabList, TabPanel, TabPanels, Tabs } from "@chakra-ui/react";
import React, { useState } from "react";
import { TabControllerSvg } from "./svg/TabControllerSvg";
import { Size, TabControllerTab } from "../component.types";
import Tab from "../Tab";

export interface TabControllerProps {
  children?: React.ReactNode;
  tabs: TabControllerTab[];
  size?: Size;
  onClick?: () => void;
}

const TabController: React.FC<TabControllerProps> = ({ children, tabs, size, ...rest }) => {
  const [tabIndex, setTabIndex] = useState(0);
  return (
    <Box {...rest} position={"relative"}>
      <Tabs variant="unstyled" defaultIndex={tabIndex} onChange={(index) => setTabIndex(index)}>
        <TabList border={'none'}>
          {tabs.map((tab, i) => (
            <Tab label={tab.label} selected={i === tabIndex} zIndex={i === tabIndex ? tabs.length : tabs.length - i} />
          ))}
        </TabList>
        <TabControllerSvg size={size || "sm"} />
        <TabPanels>
          
          {tabs.map((tab) => (
            <TabPanel>{tab.children}</TabPanel>
          ))}
        </TabPanels>
      </Tabs>
      
      {children}
    </Box>
  );
};

export default TabController;

// apps/astriarch-frontend-sveltekit/src/lib/components/astriarch/tab-controller/TabController.svelte
<script lang="ts">
  import TabControllerSvgBaselineSmall from "$lib/assets/tab-controller/TabControllerSvgBaselineSmall.svelte";
  import TabControllerSvgBaselineMedium from "$lib/assets/tab-controller/TabControllerSvgBaselineMedium.svelte";
  import TabControllerSvgBaselineLarge from "$lib/assets/tab-controller/TabControllerSvgBaselineLarge.svelte";
  import Tab from "../tab/Tab.svelte";
  import type { TabControllerTab, Size } from "../types.js";
  
  interface Props {
    tabs: TabControllerTab[];
    size?: Size;
    onclick?: () => void;
    children?: any;
  }
  
  let { 
    tabs,
    size = "sm",
    onclick,
    children,
    ...restProps 
  }: Props = $props();
  
  let tabIndex = $state(0);
  
  // Generate unique ID for SVG
  const uniqueId = Math.random().toString(36).substring(2, 15);
  
  function handleTabChange(index: number) {
    tabIndex = index;
  }
</script>

<div class="relative" {...restProps}>
  <!-- Tab headers -->
  <div class="flex border-none">
    {#each tabs as tab, i}
      <Tab
        label={tab.label}
        selected={i === tabIndex}
        onclick={() => handleTabChange(i)}
        style="z-index: {i === tabIndex ? tabs.length : tabs.length - i};"
      />
    {/each}
  </div>
  
  <!-- Tab baseline SVG -->
  <div class="relative top-0 left-2">
    {#if size === "xs" || size === "sm"}
      <TabControllerSvgBaselineSmall id={uniqueId} />
    {:else if size === "md"}
      <TabControllerSvgBaselineMedium id={uniqueId} />
    {:else}
      <TabControllerSvgBaselineLarge id={uniqueId} />
    {/if}
  </div>
  
  <!-- Tab panels -->
  <div>
    {#if tabs[tabIndex]?.children}
      {@render tabs[tabIndex].children?.()}
    {/if}
  </div>
  
  {#if children}
    {@render children()}
  {/if}
</div>
