// apps/astriarch-frontend-sveltekit/src/lib/components/astriarch/top-overview/TopOverview.svelte
<script lang="ts">
	import TopOverviewItem from '../top-overview-item/TopOverviewItem.svelte';
	import TopOverviewFrameSvg from './TopOverviewFrameSvg.svelte';
	import type { ResourceData } from '../types.js';

	export let resourceData: ResourceData = {
		total: { research: 0, energy: 0, food: 0, ore: 0, iridium: 0, production: 0 },
		perTurn: { research: 0, energy: 0, food: 0, ore: 0, iridium: 0, production: 0 }
	};
	export let population: number = 0;

	type $$Props = {
		resourceData: ResourceData;
		population: number;
		class?: string;
		[key: string]: any;
	};
</script>

<div class="relative inline-flex gap-[26px] {$$props.class || ''}" {...$$restProps}>
	<TopOverviewItem type="population" amount={population} />
	<TopOverviewItem
		type="research"
		amount={resourceData.total.research}
		amountPerTurn={resourceData.perTurn.research}
	/>
	<TopOverviewItem
		type="energy"
		amount={resourceData.total.energy}
		amountPerTurn={resourceData.perTurn.energy}
	/>
	<TopOverviewItem
		type="food"
		amount={resourceData.total.food}
		amountPerTurn={resourceData.perTurn.food}
	/>
	<TopOverviewItem
		type="ore"
		amount={resourceData.total.ore}
		amountPerTurn={resourceData.perTurn.ore}
	/>
	<TopOverviewItem
		type="iridium"
		amount={resourceData.total.iridium}
		amountPerTurn={resourceData.perTurn.iridium}
	/>

	<!-- SVG Background Frame -->
	<div class="pointer-events-none absolute top-0 left-0" style="z-index: 2;">
		<TopOverviewFrameSvg />
	</div>

	<slot />
</div>

// packages/astriarch-ui/src/components/TopOverview/index.tsx
import { Box } from "@chakra-ui/react";
import React, { useState } from "react";
import TopOverviewItem from "../TopOverviewItem";
import { TopOverviewFrameSvg } from "./svg/TopOverviewFrameSvg";

export interface PlanetResourceData {
  food: number;
  energy: number;
  research: number;
  ore: number;
  iridium: number;
  production: number;
}

export interface ResourceData {
  total: PlanetResourceData;
  perTurn: PlanetResourceData;
}

export interface TopOverviewProps {
  children?: React.ReactNode;
  resourceData: ResourceData;
  population: number;
}

const TopOverview: React.FC<TopOverviewProps> = (props) => {
  const { children, resourceData, population, ...rest } = props;
  return (
    <Box {...rest} position={"relative"} display={"inline-flex"} gap={"26px"}>
      <TopOverviewItem type="population" amount={population} />
      <TopOverviewItem
        type="research"
        amount={resourceData.total.research}
        amountPerTurn={resourceData.perTurn.research}
      />
      <TopOverviewItem type="energy" amount={resourceData.total.energy} amountPerTurn={resourceData.perTurn.energy} />
      <TopOverviewItem type="food" amount={resourceData.total.food} amountPerTurn={resourceData.perTurn.food} />
      <TopOverviewItem type="ore" amount={resourceData.total.ore} amountPerTurn={resourceData.perTurn.ore} />
      <TopOverviewItem
        type="iridium"
        amount={resourceData.total.iridium}
        amountPerTurn={resourceData.perTurn.iridium}
      />
      <Box css={{ position: "absolute", top: 0, left: 0, zIndex: 2 }}>
        <TopOverviewFrameSvg />
      </Box>
      {children}
    </Box>
  );
};

export default TopOverview;
